### ISSUE TITLE
Autostart always firing

### ISSUE THREAD

**Issue by cenk1cenk2** [loichyan/tmux-toggle-popup#10]
Hello @loichyan,

I think the `@popup-autostart` is always firing now, even though the default seems to be off, shouldn't it be checked in https://github.com/loichyan/tmux-toggle-popup/blob/4ba2befbc9f6b2107d50605853041840f1e414bc/toggle-popup.tmux#L17 here whether it is enabled or not, because I did not grasp the logic behind the environment variable I think.

**Comment by loichyan** [comment]
There was a test logic that was unexpectedly deleted in [@d95d654f](https://github.com/loichyan/tmux-toggle-popup/commit/d95d654f3eee8f1b9e86ebc000a9718305a442ce). I'm gonna fix this later.
